Repository elastic/apm-agent-js-core, pull requests merged in 2018-12, with the labels that each got.

#9 Introduce subtype and action in Spans
  .eslintrc.js
  src/performance-monitoring/capture-hard-navigation.js
  src/performance-monitoring/performance-monitoring.js
  src/performance-monitoring/span.js
  src/performance-monitoring/zone-transaction-service.js
  test/common/apm-server.spec.js
  test/performance-monitoring/performance-monitoring.spec.js
  test/performance-monitoring/span.spec.js
  test/performance-monitoring/transaction-service.spec.js
  test/performance-monitoring/transaction.spec.js
  test/performance-monitoring/zone-transaction-service.spec.js
Labels: [zube]: In Progress

#8 Unlock dependencies version in package json
  .gitignore
  .npmrc
  package-lock.json
  package.json
Labels: [zube]: In Progress

#11 chore: modify npm scripts and lint all js files
  dev-utils/run-script.js
  dev-utils/saucelabs.js
  dev-utils/test.js
  dev-utils/webdriver.js
  karma.bench.conf.js
  package.json
  src/common/patching/xhr-patch.js
  test/apm-test-config.js
  test/common/apm-server.spec.js
  test/common/config-service.spec.js
  test/common/fetch-patch.spec.js
  test/common/logging-service.spec.js
  test/common/ndjson.spec.js
  test/common/patch.js
  test/common/queue.spec.js
  test/common/service-factory.spec.js
  test/common/throttle.spec.js
  test/common/utils.spec.js
  test/common/xhr-patch.spec.js
  test/error-logging/error-logging.spec.js
  test/error-logging/stack-trace-service.spec.js
  test/mock-apm-server.js
  test/performance-monitoring/capture-hard-navigation.spec.js
  test/performance-monitoring/navigation-timing-span-snapshot.js
  test/performance-monitoring/performance-monitoring.bench.js
  test/performance-monitoring/performance-monitoring.spec.js
  test/performance-monitoring/resource-entries.js
  test/performance-monitoring/span.spec.js
  test/performance-monitoring/transaction-service.spec.js
  test/performance-monitoring/transaction.spec.js
  test/performance-monitoring/zone-service.xspec.js
  test/performance-monitoring/zone-transaction-service.spec.js
  test/performance-monitoring/zoneServiceMock.js
  test/utils/apm-server-mock.js
  test/utils/polyfill.js
  test/utils/transportMock.js
Labels: [zube]: In Progress

#14 feat: add paint timing mark to page-load transaction
  src/common/utils.js
  src/performance-monitoring/capture-hard-navigation.js
  src/performance-monitoring/transaction.js
  test/common/utils.spec.js
  test/fixtures/paint-entries.js
  test/fixtures/resource-entries.js
  test/performance-monitoring/capture-hard-navigation.spec.js
  test/performance-monitoring/performance-monitoring.spec.js
  test/performance-monitoring/transaction-service.spec.js
  test/performance-monitoring/zone-transaction-service.spec.js
Labels: [zube]: In Review

#12 chore: removing unused variables and add eslint config
  .eslintrc.js
  dev-utils/saucelabs.js
  dev-utils/test.js
  dev-utils/webdriver.js
  src/common/apm-server.js
  src/common/config-service.js
  src/common/patching/xhr-patch.js
  src/common/service-factory.js
  src/error-logging/error-logging.js
  src/performance-monitoring/transaction-service.js
  src/performance-monitoring/zone-service.js
  test/common/apm-server.spec.js
  test/common/xhr-patch.spec.js
  test/error-logging/error-logging.spec.js
  test/performance-monitoring/performance-monitoring.spec.js
  test/performance-monitoring/transaction-service.spec.js
  test/performance-monitoring/transaction.spec.js
  test/performance-monitoring/zone-service.xspec.js
  test/performance-monitoring/zone-transaction-service.spec.js
  test/performance-monitoring/zoneServiceMock.js
  test/utils/apm-server-mock.js
  test/utils/transportMock.js
Labels: [zube]: Ready

#15 chore: Update deps - webpack 4 and babel 7
  dev-utils/karma.js
  package-lock.json
  package.json
Labels: [zube]: In Progress

#17 (feat): send span sync field to apm server
  src/performance-monitoring/performance-monitoring.js
  src/performance-monitoring/span.js
  test/common/apm-server.spec.js
Labels: [zube]: In Review

#19 feat: use parentId in Spans
  dev-utils/karma.js
  src/common/utils.js
  src/performance-monitoring/capture-hard-navigation.js
  src/performance-monitoring/performance-monitoring.js
  src/performance-monitoring/span-base.js
  src/performance-monitoring/span.js
  src/performance-monitoring/transaction-service.js
  src/performance-monitoring/transaction.js
  test/performance-monitoring/performance-monitoring.spec.js
  test/performance-monitoring/transaction.spec.js
Labels: [zube]: In Progress
